export const LABELS = {
  allSynced: "All synced",
  back: "Back",
  capture: "Capture",
  changePassword: "Change password",
  confirmPassword: "Confirm password",
  continue: "Continue",
  createAccount: "Create account",
  delete: "Delete",
  emptyState: "No captured items yet.",
  emptyIncubateState: "No incubated items.",
  emptyInboxState: "No inbox items.",
  emptyNotesState: "No notes yet.",
  emptyTasksState: "No tasks yet.",
  emptyTrashState: "No trashed items.",
  exportBackup: "Export backup",
  exportingBackup: "Exporting...",
  failed: "Failed",
  incubate: "Incubate",
  inbox: "Inbox",
  importRestore: "Import / restore",
  newPassword: "New password",
  nextAction: "Next Action",
  nextActions: "Next Actions",
  notes: "Notes",
  offline: "Offline",
  openInbox: "Open Inbox",
  openList: "Open List",
  openProcess: "Process Inbox",
  openIncubate: "Open Incubate",
  openNotes: "Open Notes",
  openTasks: "Open Tasks",
  openTrash: "Open Trash",
  processInbox: "Process Inbox",
  project: "Project",
  projects: "Projects",
  rapidCapture: "Rapid capture",
  refreshSync: "Refresh sync",
  retry: "Retry",
  restoreBackup: "Restore backup",
  save: "Save",
  signIn: "Sign in",
  signInToSync: "Sign in to sync",
  signOut: "Sign out",
  settings: "Settings",
  syncing: "Syncing",
  tasks: "Tasks",
  trash: "Trash",
} as const;

export type SyncStatusLabel =
  | typeof LABELS.allSynced
  | typeof LABELS.failed
  | typeof LABELS.offline
  | typeof LABELS.signInToSync
  | typeof LABELS.syncing;
