export const LABELS = {
  allSynced: "All synced",
  back: "Back",
  calendar: "Calendar",
  capture: "Capture",
  changePassword: "Change password",
  confirmPassword: "Confirm password",
  consume: "Consume",
  continue: "Continue",
  createAccount: "Create account",
  delete: "Delete",
  doItNow: "Do it now",
  emptyCalendarState: "No scheduled items.",
  emptyIncubateState: "No incubated items.",
  emptyInboxState: "No inbox items.",
  emptyMediaState: "No consume items yet.",
  emptyNotesState: "No notes yet.",
  emptyProjectsState: "No projects yet.",
  emptyReferenceState: "No reference items yet.",
  emptyState: "No captured items yet.",
  emptyTasksState: "No tasks yet.",
  emptyTrashState: "No trashed items.",
  emptyWaitingState: "No waiting items.",
  emptyWritingState: "No writing documents yet.",
  exportBackup: "Export backup",
  exportingBackup: "Exporting...",
  failed: "Failed",
  incubate: "Incubate",
  inbox: "Inbox",
  importRestore: "Import / restore",
  markdownView: "Markdown View",
  more: "More",
  newPassword: "New password",
  nextAction: "Next Action",
  nextActions: "Next Actions",
  notes: "Notes",
  offline: "Offline",
  openCalendar: "Open Calendar",
  openInbox: "Open Inbox",
  openList: "Open List",
  openMedia: "Open Consume",
  openProcess: "Process Inbox",
  openIncubate: "Open Incubate",
  openNotes: "Open Notes",
  openProjects: "Open Projects",
  openReference: "Open Reference",
  openOriginalRoute: "Open Original Route",
  openTasks: "Open Tasks",
  openTrash: "Open Trash",
  openWaiting: "Open Waiting",
  openWriting: "Open Writing",
  processInbox: "Process Inbox",
  project: "Project",
  projects: "Projects",
  previewTitle: "Preview title",
  rapidCapture: "Rapid capture",
  reference: "Reference",
  refreshSync: "Refresh sync",
  retry: "Retry",
  restoreBackup: "Restore backup",
  save: "Save",
  saving: "Saving...",
  schedule: "Schedule",
  signIn: "Sign in",
  signInToSync: "Sign in to sync",
  signOut: "Sign out",
  settings: "Settings",
  syncing: "Syncing",
  tasks: "Tasks",
  trash: "Trash",
  waitingFor: "Waiting For",
  write: "Write",
  writing: "Writing",
  writeView: "Write View",
  read: "Read",
} as const;

export type SyncStatusLabel =
  | typeof LABELS.allSynced
  | typeof LABELS.failed
  | typeof LABELS.offline
  | typeof LABELS.signInToSync
  | typeof LABELS.syncing;
